apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qvdw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0006-tenant/tkrw-pr712-0075-0006-app/devfile-sample-qvdw@sha256:8b1484c34faa2e0e708df85b0b1cdac73a89ba5e340706128c7f8514e43530ec
        name: my-nodejs
        resources: {}
status: {}
